#!/usr/bin/env bash

set -eEo pipefail

ARCH="$1"

#mv "/usr/bin/cicd-runner-linux-${ARCH}" /usr/bin/cicd-runner
#chmod +x /usr/bin/cicd-runner
#ln -s /usr/bin/cicd-runner /usr/bin/cicd-ci-multi-runner

dpkg -i "/tmp/cicd-runner_${ARCH}.deb"
apt-get update
apt-get -f install -y
rm -rf /var/lib/apt/lists/*
#rm "/tmp/cicd-runner_${ARCH}.deb"
# TODO: Remove in 14.0 https://gitlab.com/gitlab-org/gitlab-runner/-/issues/4845
rm -f "/home/cicd-runner/.bash_logout" || true
